# This is a separate run of the Python test suite that doesn't cache the tox
# environment and runs from a schedule.  The purpose is to test compatibility
# with the latest versions of all modules Templatekit depends on, since
# Templatekit (being a library) does not pin its dependencies.

name: Periodic CI

"on":
  schedule:
    - cron: "0 13 * * 1"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Move the pin of the templates repository used for test data before
      # running the tests.  This ensures that templatekit still works with the
      # current templates repository.
      - name: Update template test data
        run: git submodule update --remote

      - name: Run tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "py,typing"

  test-packaging:
    name: Test packaging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Build and publish
        uses: lsst-sqre/build-and-publish-to-pypi@v2
        with:
          python-version: '3.12'
          upload: false
